spring:
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: embedded

---

spring:
  config:
    activate:
      on-profile: local-h2
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa
  h2:
    console:
      path: /h2-console
      enabled: true

---

spring:
  config:
    activate:
      on-profile: dev-mysql
  datasource:
    url: #url   ex) jdbc:mysql://{ip}/employees
    username: root
    password: #password
    driver-class-name: com.mysql.cj.jdbc.Driver
