spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true

---

spring:
  config:
    activate:
      on-profile: local-datasource
  jpa:
    hibernate:
      ddl-auto: create-drop

datasource:
  hikari:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:testdb
    username: sa
    password: